version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: ozon-local-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=workshop-5"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 16432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
#  redis:
#    image: redis
#    restart: always
#    container_name: local-redis
#    ports:
#      - 16379:6379
